FROM eclipse-temurin:21-jre

COPY ./*.txt /usr/app/

COPY ./target/dskrlac20_vjezba_07_dz_2_servisi-1.0.0-jar-with-dependencies.jar /usr/app/

WORKDIR /usr/app

CMD java -jar ./dskrlac20_vjezba_07_dz_2_servisi-1.0.0-jar-with-dependencies.jar
