server:
    port: 7070
javax:
    sql:
        DataSource:
            nwtis:
                # ovo je stvarni naziv koji se koristi s H2
                dataSourceClassName: org.h2.jdbcx.JdbcDataSource
                dataSource:
                    url: jdbc:h2:tcp://20.24.5.4:9092/nwtis_1
                    user: nwtis_1
                    password: nwtis#1
            h2:
                # služi kao primjer za H2
                dataSourceClassName: org.h2.jdbcx.JdbcDataSource
                dataSource:
                    url: jdbc:h2:tcp://20.24.5.4:9092/nwtis_1
                    user: nwtis_1
                    password: nwtis#1
            hsqldb:
                # NE KORISTI SE - služi kao primjer za HSQLDB
                dataSourceClassName: org.hsqldb.jdbc.JDBCDataSource
                dataSource:
                    url: jdbc:hsqldb:hsql://20.24.5.3:9001/nwtis_1
                    user: nwtis_1
                    password: nwtis#1
app:
    radari:
        adresa: 20.24.5.2
        mreznaVrata: 8000
    vozila:
        adresa: 20.24.5.2
        mreznaVrata: 8001
    kazne:
        adresa: 20.24.5.2
        mreznaVrata: 8020
webservis:
    klijenti:
        nadzor:
            baseuri: http://20.24.5.1:8080/dskrlac20_vjezba_08_dz_3_klijenti/mvc/
